apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: dev-tacos-burritos-ml
  labels:
    config-revision: bc9ad558f3ef52c843a32908e23f1544ad5239e8
spec:
  workload:
    name: tacosburritosml
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: tacos-burritos-ml-dev
    environment: dev
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./tacos-burritos-ml
  workloadVersion:
    version: v-0.0.1-48-ml-7
    commit: 6fa9605bca5c958603e7b3771f654ab77a483a05