apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: dev-tacos-burritos-ml
  labels:
    config-revision: 522c20a4db7e03a73743fad21b39c3523fd134da
spec:
  workload:
    name: tacos-burritos-ml
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: tacos-burritos-ml-dev
    environment: dev
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./tacos-burritos-ml
  workloadVersion:
    version: v-0.0.1-38
    commit: 8a8b4b82d770b96ba0588abac39d9e1e8e6c42ab