apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: dev-tacos-burritos-ml
  labels:
    config-revision: 11cb98be5adc9b4d5b25d776a21b7a20a4a8877c
spec:
  workload:
    name: tacos-burritos-ml
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: demo-team
  deploymentTarget:
    name: tacos-burritos-ml-dev
    environment: dev
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./tacos-burritos-ml
  workloadVersion:
    version: 0.0.1-70
    commit: a9ad465d99bb769f44cd4b31117d01c8e02941aa