apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: stage-tacos-burritos-ml
  labels:
    config-revision: 18cc65ab1a70887e9616da1f1a7262687e08edfe
spec:
  workload:
    name: tacos-burritos-ml
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: demo-team
  deploymentTarget:
    name: tacos-burritos-ml-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: stage
        path: ./tacos-burritos-ml
  workloadVersion:
    version: 0.0.1-75
    commit: b2167e11ed1998f7a56c990c6fa4664933cf0d72