apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: dev-tacos-burritos-ml
  labels:
    config-revision: d1cc14575e2b00e6adc089bb6051d749da68bf03
spec:
  workload:
    name: tacos-burritos-ml
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: demo-team
  deploymentTarget:
    name: tacos-burritos-ml-dev
    environment: dev
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./tacos-burritos-ml
  workloadVersion:
    version: 0.0.1-81
    commit: bc84915da4a349cc7c0d1d7a7026b789d89b209e