apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: dev-tacos-burritos-ml
  labels:
    config-revision: c040891a61af596a7a76c061222e6a8d3e31e8ee
spec:
  workload:
    name: tacos-burritos-ml
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: tacos-burritos-ml-dev
    environment: dev
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./tacos-burritos-ml
  workloadVersion:
    version: v-0.0.1-39
    commit: 41385d9ccb42d6b70dd172908f5912e2639bc148