---
# Source: TacosBurritos/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: detection-model-config
  annotations:
    version: 0.0.1-69
  
data:  
  TASK_TYPE: object_detection
  MODEL_CLASS_MAPPING: {0:patty, 1:in_progress, 2:completed_burger, 3:packaged_burger}
  MODEL_CONFIDENCE_THRESHOLD: 0.75
  WORKER_OPERATING_FPS: 6
  WORKER_TRACKER_NAME: norfair
  WORKER_TRACKER_DISTANCE_FUNCTION: kou
  WORKER_TRACKER_DISTANCE_THRESHOLD: 0.75
---
# Source: TacosBurritos/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: detection-model-service
      
spec:
  selector:
    app: detection-model
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: TacosBurritos/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-model-deployment
  annotations:
    version: 0.0.1-69
  
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: detection-model
  template:
    metadata:
      labels:
        app: detection-model
      annotations:
        version: 0.0.1-69
    spec:
      serviceAccountName: detection-model-sa
      containers:
      - name: inference-api
        image: ghcr.io/eedorenko/mlops-gitops/burger_detection_model_automl:0.0.1-69
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsUser: 10100
          runAsGroup: 10100
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        envFrom:
        - configMapRef:
            name: detection-model-config
        #read env vars from configmap
        env:
          - name: TASK_TYPE
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: task_type
          - name: MODEL_CLASS_MAPPING
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: model_class_mapping
          - name: MODEL_CONFIDENCE_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: model_confidence_threshold
          - name: WORKER_OPERATING_FPS
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_operating_fps
          - name: WORKER_TRACKER_NAME
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_tracker_name
          - name: WORKER_TRACKER_DISTANCE_FUNCTION
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_tracker_distance_function
          - name: WORKER_TRACKER_DISTANCE_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_tracker_distance_threshold
          - name: WORKER_CAMERAS
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_cameras
          - name: WORKER_ZONES
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_zones
          - name: WORKER_ZONES_ZONE_BOUNDARY_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_zones_zone_boundary_threshold
          - name: WORKER_ZONES_RENTRY_BUFFER_TIME
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_zones_reentry_buffer_time
