apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: dev-entree-detection
  labels:
    config-revision: a5d8f49e9820ea1ef28cf4a07e17b61b90e59124
spec:
  workload:
    name: entree-detection
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: kos          
        workspace:
            name: dt
  deploymentTarget:
    name: entree-detection-dev
    environment: dev
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./entree-detection
  workloadVersion:
    version: 0.0.1-101
    commit: 0f4b6e6472cabd96241e6559ad89f5eadeac71c5