apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: stage-entree-detection
  labels:
    config-revision: 4114a3e442c3bdd5d5e141312e0a045428595606
spec:
  workload:
    name: entree-detection
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: kos          
        workspace:
            name: dt
  deploymentTarget:
    name: entree-detection-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: stage
        path: ./entree-detection
  workloadVersion:
    version: 0.0.1-100
    commit: 0ec3a781edf34673aa836e5667f3d2c42fce44b9