---
# Source: TacosBurritos/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tacos-burritos-service
      
spec:
  selector:
    app: tacos-burritos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: TacosBurritos/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacos-burritos-deployment
  annotations:
    version: v-0.0.1-36
      
spec:
  strategy: 
    type: Recreate      
  replicas: 1
  selector:
    matchLabels:
      app: tacos-burritos
  template:
    metadata:
      labels:
        app: tacos-burritos      
      annotations:
        version: v-0.0.1-36
    spec:
      containers:
      - name: tacos-burritos
        image: helloworldkraftacr.azurecr.io/tacosburritos:ad15
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
