---
# Source: TacosBurritos/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tacos-burritos-ml-service
      
spec:
  selector:
    app: tacos-burritos-ml
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
# Source: TacosBurritos/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacos-burritos-ml-deployment
  annotations:
    version: v-0.0.1-56-ml-9
      
spec:
  strategy: 
    type: Recreate      
  replicas: 1
  selector:
    matchLabels:
      app: tacos-burritos-ml
  template:
    metadata:
      labels:
        app: tacos-burritos-ml      
      annotations:
        version: v-0.0.1-56-ml-9
    spec:
      containers:
      - name: tacos-burritos-ml
        image: helloworldkraftacr.azurecr.io/tacosburritos:b243
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
