apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: prod-gray-chicken-detection
  labels:
    config-revision: bde8b0bb2f2534c7b4a95991741ffb09aae2d795
spec:
  workload:
    name: tacos-burritos-ml
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: demo-team
  deploymentTarget:
    name: chicken-detection-prod-gray
    environment: prod-gray
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: prod-gray
        path: ./chicken-detection
  workloadVersion:
    version: 0.0.1-69
    commit: 44726104b4c4ab686764938b5983e3d355f412df