apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: prod-gray-chicken-detection
  labels:
    config-revision: ad1ea46b875518ec6c8cf09e76de5fb8bd980291
spec:
  workload:
    name: entree-detection
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: demo-team
  deploymentTarget:
    name: chicken-detection-prod-gray
    environment: prod-gray
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: prod-gray
        path: ./chicken-detection
  workloadVersion:
    version: 0.0.1-85
    commit: e37357e679a077007a9a1d8a0e03491a8ff28916