apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: dev-chicken-detection
  labels:
    config-revision: b4801d655e4cfb9b6360fab1048e132d5c5f0b32
spec:
  workload:
    name: entree-detection
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: kos          
        workspace:
            name: dt
  deploymentTarget:
    name: chicken-detection-dev
    environment: dev
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./chicken-detection
  workloadVersion:
    version: 0.0.1-98
    commit: c22e6ca7535d3dd5788762cf57de18a4aa7d35d0