apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: stage-burger-detection
  labels:
    config-revision: e2eef06e5bcfe0a8b24a06ea70e167060f11cdc3
spec:
  workload:
    name: burger-detection
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: kos          
        workspace:
            name: dt
  deploymentTarget:
    name: burger-detection-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: stage
        path: ./burger-detection
  workloadVersion:
    version: 0.0.1-97
    commit: 88e0cd89e19bccc2def4ae7887c606d77b729c48