apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: prod-gray-burger-detection
  labels:
    config-revision: c4fbcf4a5e60e07a5325e435b5c2d474acba0dbd
spec:
  workload:
    name: burger-detection
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: dm              
        workspace:
            name: demo-team
  deploymentTarget:
    name: burger-detection-prod-gray
    environment: prod-gray
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: prod-gray
        path: ./burger-detection
  workloadVersion:
    version: 0.0.1-80
    commit: 1bbe95013693768ebf170afd257a56d2ba967b3c