apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: stage-burger-detection
  labels:
    config-revision: 4114a3e442c3bdd5d5e141312e0a045428595606
spec:
  workload:
    name: burger-detection
    source:
        repo: https://github.com/eedorenko/mlops-gitops
        branch: main
        path: .
    application:
        name: kos          
        workspace:
            name: dt
  deploymentTarget:
    name: burger-detection-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: stage
        path: ./burger-detection
  workloadVersion:
    version: 0.0.1-101
    commit: 0f4b6e6472cabd96241e6559ad89f5eadeac71c5